// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvfpaqtmnwdsylavdfoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZnBhcXRtbndkc3lsYXZkZm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjc4NDYsImV4cCI6MjA3MzcwMzg0Nn0.n8qJLTWkSV8KIn3XGEZx1QRktxrzkF3hsA_rnaxF2EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});